language: bash

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  # create conda env
  - conda env create --file=conda_env.yaml

before_script:
  - nproc
  - free -m
  - source activate irmaenv
  - echo "will cite" | parallel --bibtex 1> /dev/null 2> /dev/null &
  - sed -i 's/SINGLE_LOCAL_PROC=\d+\t/SINGLE_LOCAL_PROC=1\t/' IRMA_RES/defaults.sh
  - sed -i 's/DOUBLE_LOCAL_PROC=\d+\t/DOUBLE_LOCAL_PROC=1\t/' IRMA_RES/defaults.sh
  - cd tests/

script:
  - ./test_run.sh
