name: irmaenv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bash >=4.4.18
  - perl >=5.26.2
  - r-base >=3.5.1
  - parallel >=20170422
  - zip >=3.0
  - pigz >=2.3.4
  - fasttree >=2.1.10
  - mafft >=7.407
  - samtools >=1.9
  - blat >=36
